"""
AegisTrace External Telemetry Correlation & Downstream Attribution Package.
"""

from core.telemetry.models import (
    TelemetrySource,
    IntegrityLevel,
    TelemetryTrustLevel,
    DeviceAttestationState,
    CanonicalEventType,
    CollectionMethod,
    BaseTelemetryEvidence,
    EndpointEvidence,
    IdentityProviderEvidence,
    NetworkEvidence,
    DLPEvent,
    CASBEvent,
    EmailGatewayEvent,
    CloudAccessEvent,
    USBTransferEvent,
    PrintEvent,
    BrowserAccessEvent,
    PublicUploadEvent,
    DeviceForensicEvidence,
    PhysicalAccessEvidence,
)
from core.telemetry.event import ForensicEvent
from core.telemetry.provider import ExternalTelemetryProvider, InMemoryTelemetryProvider
from core.telemetry.adapters import (
    EDRAdapter,
    DLPAdapter,
    IdPAdapter,
    NetworkAdapter,
    USBAdapter,
    PrintAdapter,
    PublicUploadAdapter,
    DeviceForensicsProvider,
    TelemetryNormalizationLayer,
)
from core.telemetry.graph import (
    ForensicCorrelationGraph,
    ForensicNodeType,
    ForensicEdgeType,
    ForensicGraphNode,
    ForensicGraphEdge,
)
from core.telemetry.temporal import (
    TemporalCorrelationEngine,
    TimelineEntry,
    TimelineEntryType,
    CausalValidationResult,
)
from core.telemetry.engine import (
    TelemetryCorrelationEngine,
    TelemetryEngine,
    TelemetryAttributionState,
    CandidateAttributionType,
    AttributionCandidate,
    TelemetryAttributionReport,
)
from core.telemetry.privacy import TelemetryPrivacyManager
from core.telemetry.bundle import TelemetryBundleManager
from core.telemetry.fusion_adapter import TelemetryFusionAdapter
from core.telemetry.custody import (
    UnifiedCustodyTimelineBuilder,
    CustodyTimelineReport,
    CustodyTimelineItem,
    CompoundCustodyAction,
    CustodyCausalStatus,
    ForensicAttributionLevel,
    ForensicBoundaryState,
)

__all__ = [
    "TelemetrySource",
    "IntegrityLevel",
    "TelemetryTrustLevel",
    "DeviceAttestationState",
    "CanonicalEventType",
    "CollectionMethod",
    "BaseTelemetryEvidence",
    "EndpointEvidence",
    "IdentityProviderEvidence",
    "NetworkEvidence",
    "DLPEvent",
    "CASBEvent",
    "EmailGatewayEvent",
    "CloudAccessEvent",
    "USBTransferEvent",
    "PrintEvent",
    "BrowserAccessEvent",
    "PublicUploadEvent",
    "DeviceForensicEvidence",
    "PhysicalAccessEvidence",
    "ForensicEvent",
    "ExternalTelemetryProvider",
    "InMemoryTelemetryProvider",
    "EDRAdapter",
    "DLPAdapter",
    "IdPAdapter",
    "NetworkAdapter",
    "USBAdapter",
    "PrintAdapter",
    "PublicUploadAdapter",
    "DeviceForensicsProvider",
    "TelemetryNormalizationLayer",
    "ForensicCorrelationGraph",
    "ForensicNodeType",
    "ForensicEdgeType",
    "ForensicGraphNode",
    "ForensicGraphEdge",
    "TemporalCorrelationEngine",
    "TimelineEntry",
    "TimelineEntryType",
    "CausalValidationResult",
    "TelemetryCorrelationEngine",
    "TelemetryAttributionState",
    "CandidateAttributionType",
    "AttributionCandidate",
    "TelemetryAttributionReport",
    "TelemetryPrivacyManager",
    "TelemetryBundleManager",
    "TelemetryFusionAdapter",
    "UnifiedCustodyTimelineBuilder",
    "CustodyTimelineReport",
    "CustodyTimelineItem",
    "CompoundCustodyAction",
    "CustodyCausalStatus",
    "ForensicAttributionLevel",
    "ForensicBoundaryState",
]
