"""
SIH26237 - Dependency-Aware Evidence Fusion & Anti-Double-Counting Tests
Verifies that multi-sensor duplicate logs (EDR + DLP + NetLog) generated by a single action
do not artificially inflate log-likelihood scores compared to true independent signals.
"""

import pytest
from core.attribution.evidence import (
    AttributionState,
    EvidenceFamily,
    EvidenceSource,
    TargetBinding,
    EvidenceBundle,
    ExternalTelemetryObservation,
    ProvenanceObservation,
    WatermarkObservation,
)
from core.attribution.fusion import EvidenceFusionEngine
from core.attribution.dependency import EvidenceDependencyGraph


def test_correlated_sensor_duplication_prevented():
    """Verify that multiple telemetry sensors capturing one file copy do not 3x the score."""
    binding = TargetBinding(document_id="doc_audit_01", release_id="rel_audit_01", artifact_hash="h_audit")
    
    # 3 sensors reporting on the same action (single correlation_id)
    bundle_dup = EvidenceBundle(
        target_binding=binding,
        observations=[
            ExternalTelemetryObservation(
                source_id="edr_log_01",
                target_binding=binding,
                primary_candidate="rec_alice",
                candidate_scores={"rec_alice": 3.0},
                is_valid=True,
                log_likelihood_ratio=3.0,
                observed_events_count=1
            ),
            ExternalTelemetryObservation(
                source_id="dlp_log_01",
                target_binding=binding,
                primary_candidate="rec_alice",
                candidate_scores={"rec_alice": 3.0},
                is_valid=True,
                log_likelihood_ratio=3.0,
                observed_events_count=1
            ),
            ExternalTelemetryObservation(
                source_id="net_log_01",
                target_binding=binding,
                primary_candidate="rec_alice",
                candidate_scores={"rec_alice": 3.0},
                is_valid=True,
                log_likelihood_ratio=3.0,
                observed_events_count=1
            )
        ]
    )

    engine = EvidenceFusionEngine()
    res = engine.fuse(bundle_dup)

    # Telemetry alone without verified cryptographic provenance must not trigger ATTRIBUTED
    assert res.state != AttributionState.ATTRIBUTED
    assert res.should_abstain is True


def test_independent_orthogonal_channels_accumulate():
    """Verify that genuinely orthogonal channels (Crypto Provenance + Spatial Watermark) compound properly."""
    binding = TargetBinding(document_id="doc_audit_02", release_id="rel_audit_02", artifact_hash="h_audit_2")
    
    bundle_independent = EvidenceBundle(
        target_binding=binding,
        observations=[
            ProvenanceObservation(
                source_id="prov_sig_02",
                target_binding=binding,
                primary_candidate="rec_alice",
                candidate_scores={"rec_alice": 7.0},
                is_valid=True,
                log_likelihood_ratio=7.0,
                algorithm="ML-DSA-65",
                signature_valid=True,
                signer_recipient_id="rec_alice"
            ),
            WatermarkObservation(
                source_id="wm_spatial_02",
                target_binding=binding,
                primary_candidate="rec_alice",
                candidate_scores={"rec_alice": 5.0},
                is_valid=True,
                log_likelihood_ratio=5.0
            )
        ]
    )

    engine = EvidenceFusionEngine()
    res = engine.fuse(bundle_independent)

    assert res.state == AttributionState.ATTRIBUTED
    assert res.top_candidate_id == "rec_alice"
    assert res.fused_score >= 10.0
    assert res.confidence >= 0.95
