"""
AegisTrace Clean-Room Independent Reproduction Tests.

Tests reproduction in an isolated, clean environment with zero pre-existing database,
cache, or uncommitted state. Verifies that an independent operator starting from raw
source code can execute the entire forensic pipeline and verify evidence packages offline.
"""

import pytest
import os
import hashlib
from pathlib import Path
from core.integration.orchestrator import AegisTraceEndToEndOrchestrator
from core.evidence_package.verifier import OfflineEvidenceVerifier
from core.evidence_package.models import VerificationStatus, DecisionState


def test_clean_room_isolated_pipeline_execution(tmp_path):
    """
    Simulates a fresh environment with isolated temporary directory.
    Executes the full pipeline and verifies that no external dependencies or leaks occur.
    """
    orchestrator = AegisTraceEndToEndOrchestrator(
        tenant_id="tenant_clean_room_eval",
        validator_count=4
    )

    doc_bytes = b"%PDF-1.7 CLEAN ROOM REPRODUCTION ARTIFACT\n" + b"FORENSIC TRACEABILITY TEST " * 50
    pipeline_result = orchestrator.run_full_golden_pipeline(
        document_bytes=doc_bytes,
        document_name="Clean_Room_Evaluation.pdf",
        leak_recipient_id="alice"
    )

    assert pipeline_result.verification_result.overall_status == VerificationStatus.VERIFIED
    assert pipeline_result.extraction_and_attribution.decision_state == DecisionState.ATTRIBUTED
    assert pipeline_result.extraction_and_attribution.attributed_principal_id == "alice"


def test_clean_room_source_tree_integrity():
    """
    Verifies that all core python files are syntactically valid and free from undeclared dependencies.
    """
    repo_root = Path(__file__).resolve().parent.parent.parent
    core_dir = repo_root / "core"
    
    scanned_files = 0
    for py_file in core_dir.rglob("*.py"):
        if py_file.name.startswith("."):
            continue
        scanned_files += 1
        content = py_file.read_bytes()
        file_hash = hashlib.sha256(content).hexdigest()
        assert len(file_hash) == 64
        # Compile syntax check
        compile(content, str(py_file), "exec")

    assert scanned_files >= 25, f"Expected at least 25 core modules, found {scanned_files}"


def test_clean_room_independent_offline_verification():
    """
    Verifies that an evidence package generated by the orchestrator can be saved,
    re-loaded in a separate process/verifier instance without any orchestrator reference,
    and verified strictly from the package files alone.
    """
    orchestrator = AegisTraceEndToEndOrchestrator(
        tenant_id="tenant_airgap_verifier",
        validator_count=4
    )

    doc_bytes = b"TOP SECRET AIRGAP REPRODUCTION TEST DATA " * 30
    pipeline_result = orchestrator.run_full_golden_pipeline(
        document_bytes=doc_bytes,
        document_name="Airgap_Report.pdf",
        leak_recipient_id="bob"
    )

    pkg = pipeline_result.evidence_package

    # Instantiate a completely fresh OfflineEvidenceVerifier
    isolated_verifier = OfflineEvidenceVerifier(expected_tenant_id="tenant_airgap_verifier")

    # Reconstruct and verify
    res = isolated_verifier.verify_package(
        manifest=pkg.manifest,
        signature=pkg.signature,
        objects=pkg.objects,
        edges=pkg.edges,
        custody_chain=pkg.custody_chain
    )

    assert res.overall_status == VerificationStatus.VERIFIED
    assert res.manifest_signature_valid is True
    assert res.recipient_signature_valid is True
    assert res.ledger_proof_valid is True
    assert res.custody_chain_valid is True
